import type { Metadata } from "next";
import { Londrina_Shadow, Space_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import GridBackground from "@/components/GridBackground";
import Navbar from "@/components/Navbar";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const londrinaShadow = Londrina_Shadow({
  weight: "400",
  variable: "--font-londrina",
  subsets: ["latin"]
});
const spaceMono = Space_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-space"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", londrinaShadow.variable, spaceMono.variable, "font-mono", jetbrainsMono.variable)}
    >
      <body className="min-h-full flex flex-col">
      <GridBackground />
      <Navbar />
        {children}
        </body>
    </html>
  );
}
